spring:
  application:
    name: spring-lab
server:
  port: 8080
app:
  owner: Turgynbek Amirbek
  group: IS2413
  mail:
    from: no-reply@iitu.kz
    retry-count: 3
    timeout: 5s
    enabled: true
  ui:
    theme: LIGHT
    items-per-page: 10
management:
  endpoints:
    web:
      exposure:
        include: health,env,configprops,conditions
logging:
  level:
    kz.iitu: INFO
